from datetime import datetime

from app.services.report_service import (
    ReportService
)


class ReportAgent:

    def __init__(self):

        self.report_service = ReportService()

    def build_report_content(
        self,
        title,
        query,
        analysis
    ):

        content = f"""
        CrimeIQ Intelligence Report

        Query:
        {query}

        ----------------------------------------

        Analysis Result:

        {analysis}

        ----------------------------------------

        Generated By:
        CrimeIQ AI System
        """

        return content

    def generate_intelligence_report(
        self,
        query,
        analysis
    ):

        timestamp = datetime.now().strftime(
            "%Y%m%d_%H%M%S"
        )

        title = "Crime Intelligence Report"

        filename = (
            f"crime_report_{timestamp}.pdf"
        )

        content = self.build_report_content(
            title,
            query,
            analysis
        )

        file_path = (
            self.report_service.generate_report(
                title=title,
                content=content,
                filename=filename
            )
        )

        return {
            "title": title,
            "file_path": file_path
        }